// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esrttljlyijanijtsfja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzcnR0bGpseWlqYW5panRzZmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzY1MjcsImV4cCI6MjA3MDAxMjUyN30.LntaR3oEg_AhsdEfhpWc54ytAa5xWiUSF_rN1Rr3c-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});